services:
  vault:
    image: hashicorp/vault:1.13.3
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token-demo"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    command: "server -dev -dev-root-token-id=root-token-demo"
    volumes:
      - ./docker/vault-policy.hcl:/vault/policy/vault-policy.hcl
    restart: unless-stopped
